#creates image from 
FROM node:alpine

#app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

# Bind your app to port 135
EXPOSE 3702

# CMD [ "node", "server.js" ]
CMD [ "node", "server_entregable.js" ]